// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static void aCT_BierHalen(IContext context, myfirstmodule.proxies.Entity _entity)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Entity", _entity == null ? null : _entity.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_BierHalen").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.Entity dSS_Zooi(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DSS_Zooi").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Entity.initialize(context, result);
	}
}