// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class KennislunchTest extends CustomJavaAction<java.lang.String>
{
	private java.lang.String Name;

	public KennislunchTest(IContext context, java.lang.String Name)
	{
		super(context);
		this.Name = Name;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE

		String messageToReturn = new String();
		
		if (Name.equals(null) || Name.equals("")) {
			messageToReturn = "Doe naam invoeren dan!";
		}
		else if (Name.equals("Joost")) {
			messageToReturn = "Ik ga bier halen!";
		} else {
			messageToReturn = "Ik blijf lekker zitten, Joost haalt toch al bier!";
		}
		
		return messageToReturn;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "KennislunchTest";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
